---
abstract: 'Adaptor for Redis PubSub'
author:
  - 'Tomas (t0m) Doran <bobtfish@bobtfish.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Message::Passing::Redis
name: Message-Passing-Redis
no_index:
  directory:
    - inc
    - t
requires:
  Message::Passing: 0.003
  Redis: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/suretec/Message-Passing-Redis.git
version: 0.001
x_authority: GHENRY
